
name: app-builder-ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 15, 16]
    name: Test (node ${{ matrix.node }})
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - name: Install, build and test
        run: npm ci && node bench.js
